//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_buy
    {
        public int id { get; set; }
        public int pro_id { get; set; }
        public int cus_id { get; set; }
    
        public virtual tb_customer tb_customer { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
